GET http://localhost:8080/person?number=1
###
GET http://localhost:8080/person?number=2
###
GET http://localhost:8080/person?number=2
###
GET http://localhost:8080/person?number=3
###
GET http://localhost:8080/person/add?name=Liza&surname=Ivanova&passport=12345&profession=2
###
GET http://localhost:8080/person?number=5

